### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by KrisVan** [KrisVan/Pickleball-Scheduler#24]
Components let you split the UI into independent, reusable pieces, and think about each piece in isolation.  They can each store UI templates, styling, and logic functions. Get started here with a [React Component Quickstart Guide](https://react.dev/learn/your-first-component)

### UI using MUI and Emotion 🚀 
-  Use components and styling from [MUI Templates](https://mui.com/material-ui/getting-started/templates/)
- [Sample react app using MUI](https://github.com/mui/material-ui/tree/master/examples/material-ui-cra)
- [Emotion](https://emotion.sh/docs/introduction) is a library designed for writing css styles with JavaScript. It provides powerful and predictable style composition 
---
### Components by Page
- [x] App Bar (All Pages) #30 
- [x] Home
  - [x]  Dashboard (When logged in)#52 
  - [x] Landing (When not logged in) #70 
- [x] Scheduler
  - [x]  Calendar
- [ ] Profile
  - [ ] User Info
  - [ ] Display Name change
  - [ ] Logout
- [x] About
- [x] Register
- [x] Login
- [ ] NoPage/Error 404 subpage
- [ ] No Access

### Logic
The Fetch API is used to interact with backend. You have defined your API routes, now you can retrieve them in the front end. 
[Fetch API in React](https://rapidapi.com/guides/fetch-api-react#using-the-fetch-api-in-react)
[Fetch POST w Payload](https://stackoverflow.com/questions/29775797/fetch-post-json-data)
