### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by KrisVan** [KrisVan/Pickleball-Scheduler#90]
Add an about page so that users can learn more about the website and who made it.

### Tasks
- [x]  Remove tab from App Bar component
- [x] Github icon button
- [x] Linkedin icon button
- [x] Bio text
