### ISSUE TITLE
Account Settings and Preferences

### ISSUE THREAD

**Issue by KrisVan** [KrisVan/Pickleball-Scheduler#94]
As a user, I can change my preferences and settings associated with my profile.
It can be edited by the user in the account page, accessed by profile menu.

### Acceptance Criteria
- [x] [Color](https://dev.to/martinpersson/react-material-ui-create-a-dynamic-calendar-with-integrated-todos-6cm#addtodomodal) | [MUI Color Slider](https://mui.com/material-ui/customization/color/#playground)
   - Appears as outline on profile circle 
   - Is the color of their sessions.
- [x] Theme (light/dark/system)
- [x] Change displayName: Make displayName available to sessions in EventInfoModal, UsersInInterval
- [x] Change password
- [x] Delete Account'
- [x] Refresh Login when changes confirmed
- [x] Form checking for display name, password
- [x] Response snackbar

### Tasks
- [x] Create a user preference object that contains color, and theme.
   - [x] Schema [Ways to implement user settings in db](https://culttt.com/2015/02/02/storing-user-settings-relational-database#:~:text=The%20first%20solution%20is%20to,database%20contains%20the%20user's%20settings.)
   - [x] Make a new table/model to store user settings, includes an id, User, settings
   - [x] Retrieve on login
- [x] Make displayName editable in account settings.

### Notes
- Retrieve and apply settings to context on login and update of settings.
